// Demographics, births & deaths, immigration and emigration (INE).
// Codes verified against the live Tempus3 API on 2026-10-08.

import { combine, decemberAsAnnual, splice, spliceProjection, type IndicatorDef } from "../lib/define";
import { ineSeries } from "../lib/sources";

const METHOD_BREAK_NOTE = {
  es: "Cambio de método en 2021: la Estadística de Migraciones (EM, hasta 2021) fue sustituida por la Estadística de Migraciones y Cambios de Residencia (EMCR, desde 2021), que registra más movimientos. Las dos series no son comparables.",
  en: "Method change in 2021: the Migration Statistics (EM, to 2021) were replaced by the Statistics on Migrations and Changes of Residence (EMCR, from 2021), which record more movements. The two series are not comparable.",
  ca: "Canvi de mètode el 2021: l'Estadística de Migracions (EM, fins al 2021) va ser substituïda per l'Estadística de Migracions i Canvis de Residència (EMCR, des del 2021), que registra més moviments. Les dues sèries no són comparables.",
};

const BIRTHS_ORIGIN_NOTE = {
  es: "En España no se registra el origen étnico ni la nacionalidad del recién nacido. El INE registra la nacionalidad y el país de nacimiento de los progenitores; aquí, los de la madre. Una madre nacida en el extranjero puede tener nacionalidad española.",
  en: "Spain does not record ethnic origin or the newborn's nationality. INE records the parents' nationality and country of birth; shown here, the mother's. A mother born abroad may hold Spanish nationality.",
  ca: "A Espanya no es registra l'origen ètnic ni la nacionalitat del nadó. L'INE registra la nacionalitat i el país de naixement dels progenitors; aquí, els de la mare. Una mare nascuda a l'estranger pot tenir nacionalitat espanyola.",
};

const EMCR_LABEL = { es: "Método actual (EMCR)", en: "Current method (EMCR)", ca: "Mètode actual (EMCR)" };
const EM_LABEL = { es: "Método anterior (EM)", en: "Previous method (EM)", ca: "Mètode anterior (EM)" };

export const DEMOGRAPHY_MIGRATION: IndicatorDef[] = [
  // ------------------------------------------------------------ Demographics
  {
    id: "population",
    topic: "demographics",
    unit: "persons",
    frequency: "Q",
    decimals: 0,
    yZero: false,
    periodRef: "start",
    label: { es: "Población residente", en: "Resident population", ca: "Població resident" },
    note: {
      es: "Hasta 2020, datos a 1 de enero y 1 de julio; desde 2021, trimestrales. Los datos posteriores al 1 de enero de 2025 son provisionales y se revisan cada trimestre.",
      en: "Up to 2020, figures for 1 January and 1 July; quarterly since 2021. Figures after 1 January 2025 are provisional and revised every quarter.",
      ca: "Fins al 2020, dades a 1 de gener i 1 de juliol; des del 2021, trimestrals. Les dades posteriors a l'1 de gener de 2025 són provisionals i es revisen cada trimestre.",
    },
    method: "Resident population on the first day of the period, as published by INE (Estadística Continua de Población). Pre-2021 values are intercensal estimates, rounded to whole persons.",
    resource: ineSeries({ code: "ECP320", tableId: "56934" }),
    map: (points) => points.map((p) => ({ ...p, value: Math.round(p.value) })),
  },
  {
    id: "share-65-plus",
    topic: "demographics",
    unit: "percent",
    frequency: "A",
    decimals: 1,
    yZero: true,
    periodRef: "start",
    label: { es: "Población de 65 años o más", en: "Population aged 65 and over", ca: "Població de 65 anys o més" },
    method: "Share of the population aged 65 and over on 1 January, as published by INE (Indicadores Demográficos Básicos).",
    resource: ineSeries({ code: "IDB55727", tableId: "1417" }),
  },
  {
    id: "dependency-ratio",
    topic: "demographics",
    unit: "percent",
    frequency: "A",
    decimals: 1,
    yZero: true,
    periodRef: "start",
    label: { es: "Tasa de dependencia", en: "Dependency ratio", ca: "Taxa de dependència" },
    note: {
      es: "Menores de 16 más mayores de 64, por cada 100 personas de 16 a 64 años.",
      en: "People under 16 plus people over 64, per 100 people aged 16–64.",
      ca: "Menors de 16 més majors de 64, per cada 100 persones de 16 a 64 anys.",
    },
    method: "(Population under 16 + population 65 and over) / population 16–64 × 100, on 1 January, as published by INE (Indicadores Demográficos Básicos).",
    resource: ineSeries({ code: "IDB53241", tableId: "1419" }),
  },
  {
    id: "median-age",
    topic: "demographics",
    unit: "years",
    frequency: "A",
    decimals: 1,
    yZero: false,
    periodRef: "start",
    label: { es: "Edad mediana", en: "Median age", ca: "Edat mediana" },
    method: "Median age of the population on 1 January, as published by INE (Indicadores Demográficos Básicos).",
    resource: ineSeries({ code: "IDB85061", tableId: "1725" }),
  },
  {
    id: "projected-share-65-plus",
    topic: "demographics",
    unit: "percent",
    frequency: "A",
    decimals: 1,
    yZero: true,
    periodRef: "start",
    label: {
      es: "Población de 65 años o más (proyección INE 2026–2076)",
      en: "Population aged 65 and over (INE projection 2026–2076)",
      ca: "Població de 65 anys o més (projecció INE 2026–2076)",
    },
    note: {
      es: "Proyección publicada en junio de 2026, no observación. 2026 es el año base.",
      en: "Projection published in June 2026, not an observation. 2026 is the base year.",
      ca: "Projecció publicada el juny de 2026, no observació. El 2026 és l'any base.",
    },
    method: "Projected share of the population aged 65 and over on 1 January of each year, as published by INE (Proyecciones de Población 2026–2076).",
    resource: ineSeries({ code: "PROP7463", tableId: "36666" }),
  },

  // ------------------------------------------------------------ Births & deaths
  {
    id: "births",
    topic: "births-deaths",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Nacimientos", en: "Births", ca: "Naixements" },
    note: {
      es: "Datos definitivos del Movimiento Natural de la Población; el último año procede de la estimación mensual del INE (provisional).",
      en: "Final Vital Statistics data; the latest year comes from INE's monthly estimate (provisional).",
      ca: "Dades definitives del Moviment Natural de la Població; l'últim any prové de l'estimació mensual de l'INE (provisional).",
    },
    method: "Births per year from INE's Vital Statistics (MNP). Years not yet covered by MNP use the December year-to-date total of INE's monthly birth estimate (EMN).",
    formula: "MNP births; later years = EMN year-to-date total in December",
    resources: [ineSeries({ code: "MNP17544", tableId: "6566" }), ineSeries({ code: "EMN38", tableId: "46682" })],
    combine: ([mnp, emn]) => splice(mnp, decemberAsAnnual(emn)),
  },
  {
    id: "deaths",
    topic: "births-deaths",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Defunciones", en: "Deaths", ca: "Defuncions" },
    note: {
      es: "Datos definitivos del Movimiento Natural de la Población; el último año procede de la estimación mensual del INE (provisional).",
      en: "Final Vital Statistics data; the latest year comes from INE's monthly estimate (provisional).",
      ca: "Dades definitives del Moviment Natural de la Població; l'últim any prové de l'estimació mensual de l'INE (provisional).",
    },
    method: "Deaths per year from INE's Vital Statistics (MNP). Years not yet covered by MNP use the December year-to-date total of INE's monthly death estimate (EDeS).",
    formula: "MNP deaths; later years = EDeS year-to-date total in December",
    resources: [ineSeries({ code: "MNP17542", tableId: "6566" }), ineSeries({ code: "EDES19606", tableId: "62277" })],
    combine: ([mnp, edes]) => splice(mnp, decemberAsAnnual(edes)),
  },
  {
    id: "natural-change",
    topic: "births-deaths",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Crecimiento vegetativo", en: "Natural change", ca: "Creixement vegetatiu" },
    note: {
      es: "Nacimientos menos defunciones. Para el último año (estimación), la nota de prensa del INE da una cifra algo distinta porque cuenta solo residentes.",
      en: "Births minus deaths. For the latest (estimated) year, INE's press release gives a slightly different figure because it counts residents only.",
      ca: "Naixements menys defuncions. Per a l'últim any (estimació), la nota de premsa de l'INE dona una xifra una mica diferent perquè compta només residents.",
    },
    method: "Births minus deaths per year, from the two indicators above.",
    inputs: ["births", "deaths"],
    formula: "births − deaths",
    compute: ([b, d]) => combine(b, d, (x, y) => x - y),
  },
  ...(
    [
      ["births-mother-spanish", "MNP80475152", "58929", "Madre de nacionalidad española", "Mother of Spanish nationality", "Mare de nacionalitat espanyola", "mother of Spanish nationality"],
      ["births-mother-foreign", "MNP80475151", "58929", "Madre de nacionalidad extranjera", "Mother of foreign nationality", "Mare de nacionalitat estrangera", "mother of foreign nationality"],
      ["births-mother-born-spain", "MNP80476097", "58930", "Madre nacida en España", "Mother born in Spain", "Mare nascuda a Espanya", "mother born in Spain"],
      ["births-mother-born-abroad", "MNP80476096", "58930", "Madre nacida en el extranjero", "Mother born abroad", "Mare nascuda a l'estranger", "mother born abroad"],
    ] as const
  ).map(
    ([id, code, table, es, en, ca, what]): IndicatorDef => ({
      id,
      topic: "births-deaths",
      unit: "persons",
      frequency: "A",
      decimals: 0,
      yZero: true,
      label: { es, en, ca },
      note: BIRTHS_ORIGIN_NOTE,
      method: `Births to a ${what}, national total, INE Vital Statistics (Movimiento Natural de la Población, table ${table}), final data.`,
      resource: ineSeries({ code, tableId: table }),
    }),
  ),
  {
    id: "share-births-mother-foreign",
    topic: "births-deaths",
    unit: "percent",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: { es: "Madre de nacionalidad extranjera", en: "Mother of foreign nationality", ca: "Mare de nacionalitat estrangera" },
    note: BIRTHS_ORIGIN_NOTE,
    method: "Births to mothers of foreign nationality as a share of all births (Spanish + foreign nationality), INE Vital Statistics.",
    inputs: ["births-mother-foreign", "births-mother-spanish"],
    formula: "foreign ÷ (foreign + Spanish) × 100",
    compute: ([f, e]) => combine(f, e, (x, y) => (x / (x + y)) * 100),
  },
  {
    id: "share-births-mother-born-abroad",
    topic: "births-deaths",
    unit: "percent",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: { es: "Madre nacida en el extranjero", en: "Mother born abroad", ca: "Mare nascuda a l'estranger" },
    note: BIRTHS_ORIGIN_NOTE,
    method: "Births to mothers born abroad as a share of all births (born in Spain + abroad), INE Vital Statistics.",
    inputs: ["births-mother-born-abroad", "births-mother-born-spain"],
    formula: "born abroad ÷ (born abroad + born in Spain) × 100",
    compute: ([a, e]) => combine(a, e, (x, y) => (x / (x + y)) * 100),
  },
  {
    id: "births-monthly",
    topic: "births-deaths",
    unit: "persons",
    frequency: "M",
    decimals: 0,
    yZero: true,
    label: { es: "Nacimientos", en: "Births", ca: "Naixements" },
    method: "Births per month, INE monthly birth estimate (EMN). Recent months are estimates.",
    resource: ineSeries({ code: "EMN39", tableId: "46682" }),
  },
  {
    id: "deaths-monthly",
    topic: "births-deaths",
    unit: "persons",
    frequency: "M",
    decimals: 0,
    yZero: true,
    label: { es: "Defunciones", en: "Deaths", ca: "Defuncions" },
    method: "Deaths per month, INE monthly death estimate (EDeS). Recent months are estimates.",
    resource: ineSeries({ code: "EDES19607", tableId: "62277" }),
  },
  {
    id: "fertility-rate",
    topic: "births-deaths",
    unit: "children_per_woman",
    frequency: "A",
    decimals: 2,
    yZero: true,
    label: { es: "Hijos por mujer", en: "Children per woman", ca: "Fills per dona" },
    note: {
      es: "Indicador coyuntural de fecundidad.",
      en: "Total fertility rate.",
      ca: "Indicador conjuntural de fecunditat.",
    },
    method: "Total fertility rate, as published by INE (Indicadores Demográficos Básicos).",
    resource: ineSeries({ code: "IDB72160", tableId: "1407" }),
  },
  {
    id: "life-expectancy",
    topic: "births-deaths",
    unit: "years",
    frequency: "A",
    decimals: 1,
    yZero: false,
    label: { es: "Esperanza de vida al nacer", en: "Life expectancy at birth", ca: "Esperança de vida en néixer" },
    method: "Life expectancy at birth, both sexes, as published by INE (Indicadores Demográficos Básicos).",
    resource: ineSeries({ code: "IDB53772", tableId: "1414" }),
  },

  {
    id: "life-expectancy-65",
    topic: "births-deaths",
    unit: "years",
    frequency: "A",
    decimals: 1,
    yZero: false,
    label: { es: "Esperanza de vida a los 65 años", en: "Life expectancy at 65", ca: "Esperança de vida als 65 anys" },
    note: {
      es: "Años que le quedan por vivir, de media, a quien cumple 65. Hasta el último año observado, Indicadores Demográficos Básicos; después, proyección del INE (2026–2075).",
      en: "Average years left to live for someone turning 65. Up to the latest observed year, Basic Demographic Indicators; afterwards, INE projection (2026–2075).",
      ca: "Anys que li queden per viure, de mitjana, a qui fa 65 anys. Fins a l'últim any observat, Indicadors Demogràfics Bàsics; després, projecció de l'INE (2026–2075).",
    },
    method: "Life expectancy at 65, both sexes: observed values from INE IDB (IDB54552); later years from INE Population Projections 2026–2076 (PROP7380), marked as projections.",
    formula: "observed IDB54552; years after the last observation = PROP7380 (projection)",
    resources: [ineSeries({ code: "IDB54552", tableId: "1415" }), ineSeries({ code: "PROP7380", tableId: "36659" })],
    combine: ([observed, projected]) => spliceProjection(observed, projected),
  },
  {
    id: "births-with-projection",
    topic: "births-deaths",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Nacimientos", en: "Births", ca: "Naixements" },
    note: {
      es: "Hasta el último año, nacimientos observados (MNP y estimación mensual); después, proyección del INE, que cuenta los nacidos de madres residentes en España.",
      en: "Up to the latest year, observed births (vital statistics and monthly estimate); afterwards, INE projection, which counts births to mothers resident in Spain.",
      ca: "Fins a l'últim any, naixements observats (MNP i estimació mensual); després, projecció de l'INE, que compta els nascuts de mares residents a Espanya.",
    },
    method: "Observed births (indicator 'births'); years after the last observation from INE Population Projections 2026–2076 (PROP674), marked as projections.",
    formula: "births; later years = PROP674 (projection)",
    resources: [ineSeries({ code: "MNP17544", tableId: "6566" }), ineSeries({ code: "EMN38", tableId: "46682" }), ineSeries({ code: "PROP674", tableId: "36645" })],
    combine: ([mnp, emn, proj]) => spliceProjection(splice(mnp, decemberAsAnnual(emn)), proj, 2),
  },
  {
    id: "deaths-with-projection",
    topic: "births-deaths",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Defunciones", en: "Deaths", ca: "Defuncions" },
    note: {
      es: "Hasta el último año, defunciones observadas (MNP y estimación mensual); después, proyección del INE.",
      en: "Up to the latest year, observed deaths (vital statistics and monthly estimate); afterwards, INE projection.",
      ca: "Fins a l'últim any, defuncions observades (MNP i estimació mensual); després, projecció de l'INE.",
    },
    method: "Observed deaths (indicator 'deaths'); years after the last observation from INE Population Projections 2026–2076 (PROP1430), marked as projections.",
    formula: "deaths; later years = PROP1430 (projection)",
    resources: [ineSeries({ code: "MNP17542", tableId: "6566" }), ineSeries({ code: "EDES19606", tableId: "62277" }), ineSeries({ code: "PROP1430", tableId: "36647" })],
    combine: ([mnp, edes, proj]) => spliceProjection(splice(mnp, decemberAsAnnual(edes)), proj, 2),
  },

  // ------------------------------------------------------------ Immigration
  {
    id: "foreign-born-population",
    topic: "immigration",
    unit: "persons",
    frequency: "Q",
    decimals: 0,
    yZero: true,
    periodRef: "start",
    label: { es: "Población nacida en el extranjero", en: "Foreign-born population", ca: "Població nascuda a l'estranger" },
    note: {
      es: "Incluye a personas con nacionalidad española nacidas fuera de España. Datos posteriores al 1 de enero de 2025, provisionales.",
      en: "Includes Spanish nationals born outside Spain. Figures after 1 January 2025 are provisional.",
      ca: "Inclou persones amb nacionalitat espanyola nascudes fora d'Espanya. Dades posteriors a l'1 de gener de 2025, provisionals.",
    },
    method: "Resident population born abroad on the first day of the period, as published by INE (Estadística Continua de Población).",
    resource: ineSeries({ code: "ECP239561", tableId: "79276" }),
    map: (points) => points.map((p) => ({ ...p, value: Math.round(p.value) })),
  },
  {
    id: "foreign-nationality-population",
    topic: "immigration",
    unit: "persons",
    frequency: "Q",
    decimals: 0,
    yZero: true,
    periodRef: "start",
    label: { es: "Población de nacionalidad extranjera", en: "Population with foreign nationality", ca: "Població de nacionalitat estrangera" },
    method: "Resident population with foreign nationality on the first day of the period, as published by INE (Estadística Continua de Población).",
    resource: ineSeries({ code: "ECP239404", tableId: "79276" }),
    map: (points) => points.map((p) => ({ ...p, value: Math.round(p.value) })),
  },
  {
    id: "immigration-emcr",
    topic: "immigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: EMCR_LABEL,
    note: METHOD_BREAK_NOTE,
    method: "Immigration from abroad per year, as published by INE (Estadística de Migraciones y Cambios de Residencia, from 2021).",
    resource: ineSeries({ code: "EM1770185", tableId: "69689" }),
  },
  {
    id: "immigration-em",
    topic: "immigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: EM_LABEL,
    note: METHOD_BREAK_NOTE,
    method: "Immigration from abroad per year, as published by INE (Estadística de Migraciones, 2008–2021, discontinued).",
    resource: ineSeries({ code: "EM999783", tableId: "24294" }),
  },
  {
    id: "net-migration-emcr",
    topic: "immigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: EMCR_LABEL,
    note: METHOD_BREAK_NOTE,
    method: "Immigration from abroad minus emigration abroad per year, as published by INE (EMCR, from 2021).",
    resource: ineSeries({ code: "EM2258843", tableId: "69758" }),
  },
  {
    id: "net-migration-em",
    topic: "immigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: EM_LABEL,
    note: METHOD_BREAK_NOTE,
    method: "Immigration from abroad minus emigration abroad per year, as published by INE (EM, 2008–2021, discontinued).",
    resource: ineSeries({ code: "EM798349", tableId: "24310" }),
  },

  // ------------------------------------------------------------ Emigration
  {
    id: "emigration-emcr",
    topic: "emigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: EMCR_LABEL,
    note: METHOD_BREAK_NOTE,
    method: "Emigration abroad per year, all nationalities, as published by INE (EMCR, from 2021).",
    resource: ineSeries({ code: "EM1848386", tableId: "69704" }),
  },
  {
    id: "emigration-em",
    topic: "emigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: EM_LABEL,
    note: METHOD_BREAK_NOTE,
    method: "Emigration abroad per year, all nationalities, as published by INE (EM, 2008–2021, discontinued).",
    resource: ineSeries({ code: "EM802357", tableId: "24302" }),
  },
  {
    id: "emigration-spanish-emcr",
    topic: "emigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Nacionalidad española", en: "Spanish nationality", ca: "Nacionalitat espanyola" },
    method: "Emigration abroad of Spanish nationals per year, as published by INE (EMCR, from 2021).",
    resource: ineSeries({ code: "EM1848362", tableId: "69704" }),
  },
  {
    id: "emigration-foreign-emcr",
    topic: "emigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Nacionalidad extranjera", en: "Foreign nationality", ca: "Nacionalitat estrangera" },
    method: "Emigration abroad of foreign nationals per year, as published by INE (EMCR, from 2021).",
    resource: ineSeries({ code: "EM1850018", tableId: "69704" }),
  },
  {
    id: "spaniards-abroad",
    topic: "emigration",
    unit: "persons",
    frequency: "A",
    decimals: 0,
    yZero: true,
    periodRef: "start",
    label: { es: "Españoles residentes en el extranjero", en: "Spanish nationals living abroad", ca: "Espanyols residents a l'estranger" },
    note: {
      es: "Cuenta personas con nacionalidad española inscritas en el extranjero, hayan nacido o no en España. No es una medida de emigración.",
      en: "Counts Spanish nationals registered abroad, whether or not they were born in Spain. It is not a measure of emigration.",
      ca: "Compta persones amb nacionalitat espanyola inscrites a l'estranger, hagin nascut o no a Espanya. No és una mesura d'emigració.",
    },
    method: "Spanish nationals registered as resident abroad on 1 January, as published by INE (Padrón de Españoles Residentes en el Extranjero, PERE).",
    resource: ineSeries({ code: "PERE11798", tableId: "79675" }),
  },
];
