// Economy and labour indicators (INE). Series codes verified against the live
// Tempus3 API on 2026-10-08; EPA codes replace EPA815 etc., which stopped at 2023Q4.

import type { IndicatorDef } from "../lib/define";
import { ineSeries } from "../lib/sources";

export const ECONOMY_LABOUR: IndicatorDef[] = [
  {
    id: "gdp-growth-quarterly",
    topic: "economy",
    unit: "percent_change",
    frequency: "Q",
    decimals: 1,
    yZero: true,
    label: {
      es: "Crecimiento del PIB real (interanual)",
      en: "Real GDP growth (year on year)",
      ca: "Creixement del PIB real (interanual)",
    },
    method: "Year-on-year change in chain-linked volume GDP, seasonally and calendar adjusted, as published by INE (Contabilidad Nacional Trimestral).",
    resource: ineSeries({ code: "CNTR6654", tableId: "67822" }),
  },
  {
    id: "gdp-growth-annual",
    topic: "economy",
    unit: "percent_change",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: {
      es: "Crecimiento del PIB real (anual)",
      en: "Real GDP growth (annual)",
      ca: "Creixement del PIB real (anual)",
    },
    note: {
      es: "Serie Total Nacional de la Contabilidad Regional; coincide con la Contabilidad Nacional Anual.",
      en: "National total from INE's regional accounts; identical to the annual national accounts.",
      ca: "Sèrie Total Nacional de la Comptabilitat Regional; coincideix amb la Comptabilitat Nacional Anual.",
    },
    method: "Annual change in chain-linked volume GDP, as published by INE.",
    resource: ineSeries({ code: "CRE47525", tableId: "80111" }),
  },
  {
    id: "gdp-per-capita",
    topic: "economy",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "PIB por habitante", en: "GDP per person", ca: "PIB per habitant" },
    note: {
      es: "Euros corrientes (sin descontar la inflación).",
      en: "Current euros (not adjusted for inflation).",
      ca: "Euros corrents (sense descomptar la inflació).",
    },
    method: "GDP at current prices divided by population, as published by INE.",
    resource: ineSeries({ code: "CRE47377", tableId: "80110" }),
  },
  {
    id: "cpi-inflation-monthly",
    topic: "economy",
    unit: "percent_change",
    frequency: "M",
    decimals: 1,
    yZero: true,
    label: { es: "Inflación (IPC, interanual)", en: "Inflation (CPI, year on year)", ca: "Inflació (IPC, interanual)" },
    method: "Annual change in the general Consumer Price Index for each month, as published by INE. Flash estimates are marked provisional.",
    resource: ineSeries({ code: "IPC290750", tableId: "76134" }),
  },
  {
    id: "cpi-inflation-annual",
    topic: "economy",
    unit: "percent_change",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: { es: "Inflación (IPC, media anual)", en: "Inflation (CPI, annual average)", ca: "Inflació (IPC, mitjana anual)" },
    method: "Change in the annual average of the general Consumer Price Index, as published by INE.",
    resource: ineSeries({ code: "IPC318622", tableId: "76144" }),
  },
  {
    id: "unemployment-rate",
    topic: "economy",
    unit: "percent",
    frequency: "Q",
    decimals: 2,
    yZero: true,
    label: { es: "Tasa de paro", en: "Unemployment rate", ca: "Taxa d'atur" },
    note: {
      es: "Personas de 16 años o más. INE revisó 2021–2023 con la nueva base de población.",
      en: "People aged 16 and over. INE revised 2021–2023 with the new population base.",
      ca: "Persones de 16 anys o més. L'INE va revisar 2021–2023 amb la nova base de població.",
    },
    method: "Unemployed as a share of the active population, quarterly, as published by INE (EPA). Not seasonally adjusted.",
    resource: ineSeries({ code: "EPA423474", tableId: "65219" }),
  },
  {
    id: "employed",
    topic: "economy",
    unit: "persons",
    frequency: "Q",
    decimals: 0,
    yZero: false,
    label: { es: "Personas ocupadas", en: "People in employment", ca: "Persones ocupades" },
    method: "Employed people, quarterly, as published by INE (EPA) in thousands and converted to persons. Not seasonally adjusted.",
    resource: ineSeries({ code: "EPA387796", tableId: "65109", scale: "1E3" }),
  },
  {
    id: "activity-rate",
    topic: "labour",
    unit: "percent",
    frequency: "Q",
    decimals: 2,
    yZero: true,
    label: { es: "Tasa de actividad", en: "Activity rate", ca: "Taxa d'activitat" },
    note: {
      es: "Activos sobre la población de 16 años o más.",
      en: "Active population as a share of people aged 16 and over.",
      ca: "Actius sobre la població de 16 anys o més.",
    },
    method: "Active population (employed + unemployed) as a share of the population aged 16+, quarterly, as published by INE (EPA).",
    resource: ineSeries({ code: "EPA388079", tableId: "65081" }),
  },
  {
    id: "unemployment-rate-men",
    topic: "labour",
    unit: "percent",
    frequency: "Q",
    decimals: 2,
    yZero: true,
    label: { es: "Hombres", en: "Men", ca: "Homes" },
    method: "Unemployment rate of men aged 16+, quarterly, as published by INE (EPA).",
    resource: ineSeries({ code: "EPA423488", tableId: "65219" }),
  },
  {
    id: "unemployment-rate-women",
    topic: "labour",
    unit: "percent",
    frequency: "Q",
    decimals: 2,
    yZero: true,
    label: { es: "Mujeres", en: "Women", ca: "Dones" },
    method: "Unemployment rate of women aged 16+, quarterly, as published by INE (EPA).",
    resource: ineSeries({ code: "EPA423501", tableId: "65219" }),
  },
  {
    id: "youth-unemployment-rate",
    topic: "labour",
    unit: "percent",
    frequency: "Q",
    decimals: 2,
    yZero: true,
    label: { es: "Tasa de paro de menores de 25 años", en: "Unemployment rate, under 25", ca: "Taxa d'atur de menors de 25 anys" },
    method: "Unemployment rate of people aged 16–24, quarterly, as published by INE (EPA).",
    resource: ineSeries({ code: "EPA452436", tableId: "65334" }),
  },
  {
    id: "temporary-contract-share",
    topic: "labour",
    unit: "percent",
    frequency: "Q",
    decimals: 1,
    yZero: true,
    label: {
      es: "Asalariados con contrato temporal",
      en: "Employees on temporary contracts",
      ca: "Assalariats amb contracte temporal",
    },
    method: "Employees with a temporary contract as a share of all employees (tasa de temporalidad), quarterly, as published by INE (EPA).",
    resource: ineSeries({ code: "EPA416256", tableId: "65194" }),
  },
  {
    id: "median-salary",
    topic: "labour",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Salario bruto anual mediano", en: "Median gross annual salary", ca: "Salari brut anual medià" },
    note: {
      es: "Euros corrientes. Encuesta Anual de Estructura Salarial; el dato de cada año se publica con unos 18 meses de retraso.",
      en: "Current euros. Annual Wage Structure Survey; each year is published about 18 months later.",
      ca: "Euros corrents. Enquesta Anual d'Estructura Salarial; cada any es publica uns 18 mesos després.",
    },
    method: "Median gross annual earnings per worker, both sexes, as published by INE (Encuesta Anual de Estructura Salarial).",
    resource: ineSeries({ code: "EAES738", tableId: "28191" }),
  },
];
