// Housing and public finances. INE and Eurostat via API; Ministerio de Transportes,
// MIVAU and AEAT via downloaded spreadsheets; Banco de España via its series API.
// Identifiers verified on 2026-10-08.

import { combine, type IndicatorDef } from "../lib/define";
import { aeatAnnualNet, annualSums, aparejadoresMonthly, mivauAnnualTotal, rolling12, sheetRows } from "../lib/parsers";
import { bdeSeries, eurostat, file, ineSeries } from "../lib/sources";

const TRANSPORTES_LICENCE = "Open data licence of the Ministerio de Transportes y Movilidad Sostenible (reuse with attribution)";

const certificados = file({
  sourceId: "transportes-certificados-fin-obra",
  group: "transportes",
  filename: "09011600.XLS",
  url: "https://apps.fomento.gob.es/BoletinOnline/sedal/09011600.XLS",
  humanUrl:
    "https://www.transportes.gob.es/informacion-para-el-ciudadano/informacion-estadistica/construccion/obras-en-edificacion-visados-de-direccion-de-obra-de-los-colegios-de-arquitectos-tecnicos",
  publisher: "Ministerio de Transportes y Movilidad Sostenible",
  dataset: "Obras en edificación: certificaciones de fin de obra (Colegios de Aparejadores)",
  tableId: "09011600",
  licence: TRANSPORTES_LICENCE,
  attribution: "Fuente: Ministerio de Transportes y Movilidad Sostenible, a partir de los Colegios de Aparejadores",
  notes: "Sheet APAREJA_15, TOTAL NACIONAL; column E = total dwellings with a certificate of completion.",
  parse: (body) => {
    const monthly = aparejadoresMonthly(sheetRows(body, "APAREJA_15"), { yearCol: 1, monthCol: 3, valueCol: 4 });
    return { annual: annualSums(monthly), rolling12: rolling12(monthly) };
  },
});

const protegidaAnual = file({
  sourceId: "mivau-vivienda-protegida-calificaciones-definitivas",
  group: "mivau",
  filename: "31306000.XLS",
  url: "https://apps.fomento.gob.es/BoletinOnline2/sedal/31306000.XLS",
  humanUrl: "https://www.mivau.gob.es/el-ministerio/observatorios-y-estadisticas/estadisticas/vivienda-rehabilitacion-protegidas",
  publisher: "Ministerio de Vivienda y Agenda Urbana (MIVAU)",
  dataset: "Vivienda protegida: calificaciones definitivas (tabla 1.6, anual)",
  tableId: "31306000",
  licence: "Reuse with attribution (MIVAU open data; also published on datos.gob.es under CC BY 4.0)",
  attribution: "Fuente: Ministerio de Vivienda y Agenda Urbana",
  notes: "Sheet 'Tabla 1.6.', TOTAL NACIONAL row.",
  parse: (body) => ({ annual: mivauAnnualTotal(sheetRows(body, "Tabla 1.6.")) }),
});

const aeat = file({
  sourceId: "aeat-recaudacion-tributaria",
  group: "aeat",
  filename: "Cuadros_estadisticos_series_es_es.xlsx",
  url: "https://sede.agenciatributaria.gob.es/static_files/Sede/Tema/Estadisticas/Recaudacion_Tributaria/Informes_mensuales/Cuadros_estadisticos_series_es_es.xlsx",
  humanUrl: "https://sede.agenciatributaria.gob.es/Sede/datosabiertos/catalogo/hacienda/Informe_mensual_de_Recaudacion_Tributaria.shtml",
  publisher: "Agencia Tributaria (AEAT)",
  dataset: "Informe mensual de recaudación tributaria: cuadros estadísticos y series",
  tableId: "Ingresos tributarios",
  licence: "Reuse permitted with attribution and last-update date (AEAT legal notice)",
  attribution: "Fuente: Agencia Estatal de Administración Tributaria",
  notes: "Sheet 'Ingresos tributarios', annual block in million euros, net revenue ('Ingresos netos'). Excludes Basque and Navarre foral taxes, local taxes and social contributions.",
  parse: (body) => {
    const rows = sheetRows(body, "Ingresos tributarios");
    return {
      total: aeatAnnualNet(rows, "Ingresos tributarios"),
      irpf: aeatAnnualNet(rows, "Impuesto sobre la Renta de las Personas Físicas"),
      iva: aeatAnnualNet(rows, "Impuesto sobre el Valor Añadido"),
      sociedades: aeatAnnualNet(rows, "Impuesto sobre Sociedades"),
    };
  },
});

const AEAT_NOTE = {
  es: "Ingresos netos gestionados por la AEAT, en euros corrientes. Excluye tributos forales de País Vasco y Navarra, tributos locales y cotizaciones sociales.",
  en: "Net revenue managed by AEAT, current euros. Excludes Basque and Navarre foral taxes, local taxes and social contributions.",
  ca: "Ingressos nets gestionats per l'AEAT, en euros corrents. Exclou els tributs forals del País Basc i Navarra, els tributs locals i les cotitzacions socials.",
};

export const HOUSING_FINANCE: IndicatorDef[] = [
  // ------------------------------------------------------------ Housing
  {
    id: "house-prices",
    topic: "housing",
    unit: "percent_change",
    frequency: "Q",
    decimals: 1,
    yZero: true,
    label: { es: "Precio de la vivienda (interanual)", en: "House prices (year on year)", ca: "Preu de l'habitatge (interanual)" },
    method: "Year-on-year change in INE's House Price Index (IPV), general, quarterly.",
    resource: ineSeries({ code: "IPV1376", tableId: "80270" }),
  },
  {
    id: "house-prices-annual",
    topic: "housing",
    unit: "percent_change",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: { es: "Precio de la vivienda (media anual)", en: "House prices (annual average)", ca: "Preu de l'habitatge (mitjana anual)" },
    method: "Change in the annual average of INE's House Price Index (IPV), general.",
    resource: ineSeries({ code: "IPV1279", tableId: "79540" }),
  },
  {
    id: "rent-index",
    topic: "housing",
    unit: "index",
    frequency: "A",
    decimals: 1,
    yZero: false,
    label: { es: "Índice de precios del alquiler (2015 = 100)", en: "Rental price index (2015 = 100)", ca: "Índex de preus del lloguer (2015 = 100)" },
    note: {
      es: "Índice de Precios de Vivienda en Alquiler (IPVA), elaborado con datos tributarios; se publica con más de un año de retraso.",
      en: "Rental Housing Price Index (IPVA), built from tax records; published more than a year after the reference year.",
      ca: "Índex de Preus d'Habitatge en Lloguer (IPVA), elaborat amb dades tributàries; es publica amb més d'un any de retard.",
    },
    method: "INE Rental Housing Price Index (IPVA), national, base 2015 = 100.",
    resource: ineSeries({ code: "IPVA4962", tableId: "59056" }),
  },
  {
    id: "rent-cpi",
    topic: "housing",
    unit: "percent_change",
    frequency: "M",
    decimals: 1,
    yZero: true,
    label: {
      es: "Alquiler de vivienda habitual en el IPC (interanual)",
      en: "Rent of main residence in the CPI (year on year)",
      ca: "Lloguer d'habitatge habitual a l'IPC (interanual)",
    },
    method: "Year-on-year change of the CPI subclass 'actual rentals paid by tenants for main residence', as published by INE.",
    resource: ineSeries({ code: "IPC291806", tableId: "76128" }),
  },
  {
    id: "dwellings-completed-12m",
    topic: "housing",
    unit: "dwellings",
    frequency: "M",
    decimals: 0,
    yZero: true,
    label: {
      es: "Viviendas terminadas (últimos 12 meses)",
      en: "Dwellings completed (last 12 months)",
      ca: "Habitatges acabats (últims 12 mesos)",
    },
    note: {
      es: "Certificados de fin de obra de los Colegios de Aparejadores, todas las promociones. Cada punto suma los 12 meses anteriores.",
      en: "Certificates of completion from the Colegios de Aparejadores, all developers. Each point is the sum of the previous 12 months.",
      ca: "Certificats de final d'obra dels Col·legis d'Aparelladors, totes les promocions. Cada punt suma els 12 mesos anteriors.",
    },
    method: "Sum of the 12 monthly totals ending in each month (TOTAL NACIONAL, column 'total viviendas').",
    formula: "Σ dwellings with a completion certificate, months t−11 … t",
    resource: certificados.series("rolling12"),
  },
  {
    id: "dwellings-completed",
    topic: "housing",
    unit: "dwellings",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Viviendas terminadas al año", en: "Dwellings completed per year", ca: "Habitatges acabats per any" },
    method: "Calendar-year sum of monthly certificates of completion (Colegios de Aparejadores, TOTAL NACIONAL).",
    formula: "Σ monthly dwellings with a completion certificate, January–December",
    resource: certificados.series("annual"),
  },
  {
    id: "protected-dwellings",
    topic: "housing",
    unit: "dwellings",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: {
      es: "Viviendas protegidas terminadas (calificaciones definitivas)",
      en: "Protected (subsidised) dwellings completed",
      ca: "Habitatges protegits acabats (qualificacions definitives)",
    },
    note: {
      es: "Viviendas con calificación definitiva de protección oficial, de promotores públicos y privados.",
      en: "Dwellings receiving final 'protected housing' status, from public and private developers.",
      ca: "Habitatges amb qualificació definitiva de protecció oficial, de promotors públics i privats.",
    },
    method: "Final protected-housing certifications per year, TOTAL NACIONAL, as published by MIVAU (table 1.6).",
    resource: protegidaAnual.series("annual"),
  },
  {
    id: "price-to-income",
    topic: "housing",
    unit: "ratio",
    frequency: "Q",
    decimals: 1,
    yZero: true,
    label: {
      es: "Años de renta para comprar una vivienda",
      en: "Years of income to buy a home",
      ca: "Anys de renda per comprar un habitatge",
    },
    note: {
      es: "Precio de una vivienda libre tipo dividido por la renta bruta disponible mediana por hogar (Banco de España).",
      en: "Price of a typical free-market dwelling divided by median gross household income (Banco de España).",
      ca: "Preu d'un habitatge lliure tipus dividit per la renda bruta disponible mediana per llar (Banco de España).",
    },
    method: "Banco de España housing-market indicator 'precio de la vivienda / renta bruta por hogar', quarterly.",
    resource: bdeSeries({
      code: "D_TKB57110_IPV",
      tableId: "si_1_5",
      dataset: "Indicadores del mercado de la vivienda: accesibilidad",
      humanUrl: "https://www.bde.es/webbe/es/estadisticas/temas/indicadores-mercado-vivienda.html",
    }),
  },
  {
    id: "households-renting",
    topic: "housing",
    unit: "percent",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: { es: "Hogares que viven de alquiler", en: "Households renting their home", ca: "Llars que viuen de lloguer" },
    note: {
      es: "Alquiler a precio de mercado más alquiler inferior al de mercado. Excluye la cesión gratuita.",
      en: "Market-price rent plus below-market rent. Excludes rent-free use.",
      ca: "Lloguer a preu de mercat més lloguer inferior al de mercat. Exclou la cessió gratuïta.",
    },
    method: "Sum of the shares of households renting at market price and below market price, as published by INE (Encuesta de Condiciones de Vida).",
    formula: "market-price rent % + below-market rent %",
    resources: [ineSeries({ code: "ECV2643", tableId: "9997" }), ineSeries({ code: "ECV2642", tableId: "9997" })],
    combine: ([market, below]) => combine(market, below, (a, b) => a + b).map((p) => ({ ...p, from: 0 })),
  },

  // ------------------------------------------------------------ Public finances & taxes
  {
    id: "gdp-nominal",
    topic: "public-finances",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "PIB nominal", en: "Nominal GDP", ca: "PIB nominal" },
    method: "GDP at current market prices, million euros converted to euros, from Eurostat (nama_10_gdp, B1GQ, CP_MEUR).",
    resource: eurostat({
      sourceId: "eurostat-nama-10-gdp-es",
      dataset: "nama_10_gdp",
      filters: { geo: "ES", na_item: "B1GQ", unit: "CP_MEUR" },
      datasetLabel: "GDP and main components (output, expenditure and income)",
    }),
    map: (points) => points.map((p) => ({ ...p, value: p.value * 1e6 })),
  },
  {
    id: "tax-revenue-gdp",
    topic: "public-finances",
    unit: "percent_gdp",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: {
      es: "Impuestos y cotizaciones sociales",
      en: "Taxes and social contributions",
      ca: "Impostos i cotitzacions socials",
    },
    note: {
      es: "Total de impuestos y cotizaciones sociales netas de todas las administraciones y de las instituciones de la UE (definición de Eurostat).",
      en: "Total taxes and net social contributions received by all levels of government and EU institutions (Eurostat definition).",
      ca: "Total d'impostos i cotitzacions socials netes de totes les administracions i de les institucions de la UE (definició d'Eurostat).",
    },
    method: "Eurostat gov_10a_taxag, item D2_D5_D91_D61_M_D995, sector S13_S212, % of GDP.",
    resource: eurostat({
      sourceId: "eurostat-gov-10a-taxag-es",
      dataset: "gov_10a_taxag",
      filters: { geo: "ES", unit: "PC_GDP", sector: "S13_S212", na_item: "D2_D5_D91_D61_M_D995" },
      datasetLabel: "Main national accounts tax aggregates",
    }),
  },
  {
    id: "tax-revenue-aeat",
    topic: "public-finances",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Recaudación tributaria (AEAT)", en: "Tax revenue collected (AEAT)", ca: "Recaptació tributària (AEAT)" },
    note: AEAT_NOTE,
    method: "Net tax revenue, annual total, as published by AEAT (million euros, converted to euros).",
    resource: aeat.series("total"),
  },
  {
    id: "revenue-irpf",
    topic: "public-finances",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "IRPF", en: "Personal income tax (IRPF)", ca: "IRPF" },
    note: AEAT_NOTE,
    method: "Net revenue from personal income tax (IRPF), as published by AEAT.",
    resource: aeat.series("irpf"),
  },
  {
    id: "revenue-iva",
    topic: "public-finances",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "IVA", en: "VAT (IVA)", ca: "IVA" },
    note: AEAT_NOTE,
    method: "Net revenue from value added tax (IVA), as published by AEAT.",
    resource: aeat.series("iva"),
  },
  {
    id: "revenue-sociedades",
    topic: "public-finances",
    unit: "eur",
    frequency: "A",
    decimals: 0,
    yZero: true,
    label: { es: "Impuesto sobre Sociedades", en: "Corporate income tax", ca: "Impost sobre Societats" },
    note: AEAT_NOTE,
    method: "Net revenue from corporate income tax (Impuesto sobre Sociedades), as published by AEAT.",
    resource: aeat.series("sociedades"),
  },
  {
    id: "deficit-gdp",
    topic: "public-finances",
    unit: "percent_gdp",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: {
      es: "Saldo de las administraciones públicas",
      en: "General government balance",
      ca: "Saldo de les administracions públiques",
    },
    note: {
      es: "Valores negativos = déficit. Notificación del Protocolo de Déficit Excesivo.",
      en: "Negative values = deficit. Excessive Deficit Procedure notification.",
      ca: "Valors negatius = dèficit. Notificació del Protocol de Dèficit Excessiu.",
    },
    method: "Net lending (+) / net borrowing (−) of general government, % of GDP, Eurostat gov_10dd_edpt1 (B9, S13).",
    resource: eurostat({
      sourceId: "eurostat-gov-10dd-edpt1-b9-es",
      dataset: "gov_10dd_edpt1",
      filters: { geo: "ES", unit: "PC_GDP", sector: "S13", na_item: "B9" },
      datasetLabel: "Government deficit/surplus, debt and associated data",
    }),
  },
  {
    id: "debt-gdp",
    topic: "public-finances",
    unit: "percent_gdp",
    frequency: "A",
    decimals: 1,
    yZero: true,
    label: { es: "Deuda pública", en: "Government debt", ca: "Deute públic" },
    note: {
      es: "Deuda bruta consolidada de las administraciones públicas (Protocolo de Déficit Excesivo).",
      en: "Consolidated gross general government debt (Excessive Deficit Procedure).",
      ca: "Deute brut consolidat de les administracions públiques (Protocol de Dèficit Excessiu).",
    },
    method: "General government consolidated gross debt, % of GDP, Eurostat gov_10dd_edpt1 (GD, S13).",
    resource: eurostat({
      sourceId: "eurostat-gov-10dd-edpt1-gd-es",
      dataset: "gov_10dd_edpt1",
      filters: { geo: "ES", unit: "PC_GDP", sector: "S13", na_item: "GD" },
      datasetLabel: "Government deficit/surplus, debt and associated data",
    }),
  },
  {
    id: "debt-gdp-quarterly",
    topic: "public-finances",
    unit: "percent_gdp",
    frequency: "Q",
    decimals: 1,
    yZero: true,
    label: { es: "Deuda pública (trimestral)", en: "Government debt (quarterly)", ca: "Deute públic (trimestral)" },
    method: "General government consolidated gross debt, % of GDP, quarterly, Eurostat gov_10q_ggdebt (GD, S13).",
    resource: eurostat({
      sourceId: "eurostat-gov-10q-ggdebt-es",
      dataset: "gov_10q_ggdebt",
      filters: { geo: "ES", unit: "PC_GDP", sector: "S13", na_item: "GD" },
      datasetLabel: "Quarterly government debt",
    }),
  },
  {
    id: "debt-eur-quarterly",
    topic: "public-finances",
    unit: "eur",
    frequency: "Q",
    decimals: 0,
    yZero: true,
    label: { es: "Deuda pública en euros", en: "Government debt in euros", ca: "Deute públic en euros" },
    note: {
      es: "Euros corrientes, sin ajustar por inflación ni por el tamaño de la economía; la deuda en porcentaje del PIB es la medida que usan las reglas de la UE.",
      en: "Current euros, not adjusted for inflation or the size of the economy; debt as a share of GDP is the measure used by EU rules.",
      ca: "Euros corrents, sense ajustar per la inflació ni per la mida de l'economia; el deute en percentatge del PIB és la mesura que fan servir les regles de la UE.",
    },
    method: "General government consolidated gross debt, million euros × 1,000,000, quarterly, Eurostat gov_10q_ggdebt (GD, S13).",
    resource: eurostat({
      sourceId: "eurostat-gov-10q-ggdebt-eur-es",
      dataset: "gov_10q_ggdebt",
      filters: { geo: "ES", unit: "MIO_EUR", sector: "S13", na_item: "GD" },
      datasetLabel: "Quarterly government debt",
    }),
    map: (points) => points.map((p) => ({ ...p, value: p.value * 1e6 })),
  },
];
